all: install

build:
	src/build.sh
install:
	src/install.sh
uninstall:
	src/uninstall.sh
test:
	src/test.sh
man:
	man docs/man/man3/guess.c.3
help:
	browse docs/html/index.html
clean:
	rm -rf build docs po/ru/LC_MESSAGES
	rm -f guess

